### ISSUE TITLE
Remove watermark

### ISSUE THREAD

**Issue by gbenroscience** [pdfcpu/pdfcpu#103]
How do I stamp a pdf page that is already watermarked?
 I cant seem to do that.
This [link](https://www.bookstack.cn/read/pdfcpu/825ef44155aac020.md) says that stamping or watermarks can be done exactly once.

Can I delete, replace or edit an existing watermark then?

**Comment by hhrutter** [comment]
This is not the official documentation.

The official documentation is [http://pdfcpu.io/core/stamp](here) and yes you can stamp or watermark a PDF file exactly once.

**Comment by olekukonko** [comment]
@hhrutter can you kindly clarify the following 

-`Delete is not there but doable` How is this possible? 
- Can `stamp` or `watermark` also be extracted?

**Comment by hhrutter** [comment]
What I mean is we can add `pdfcpu remove stamp` as a new pdfcpu command.

Stamp/watermark extraction is tricky because a  stamp/watermark may be text, an image or a PDF page.

**Comment by olekukonko** [comment]
@hhrutter I agree with you 100%, however, 

- we can start with `pdfcpu remove stamp` (also support via api) 
- extraction can have some limitation which you can only extract to `pdf` or `transparent png` if that is possible because I think "text" is what introduces the complications you are envisaging. (Kindly correct if am wrong) 

Regards.

**Comment by hhrutter** [comment]
fixed with v0.2.5
