### ISSUE TITLE
Add link annotations

### ISSUE THREAD

**Issue by mpup371** [pdfcpu/pdfcpu#115]
Hi,
using pdfcpu API, based on code example, I was able to open a pdf file, add links into it and write the new file. Thanks to make a library that can do both read and write pdf.
When I try to do the same with images like png, I find only private functions. I am not sure if these functions are for internal use only, but it would be nice if there was such functionality in the API.
On the documentation, it would be nice if there was a "quick start" manual explaining the basics of pdf manipulation with pdfcpu for beginners in the pdf world.

regards,
jf

**Comment by hhrutter** [comment]
Hello,

The main job of pdfcpu is processing existing PDFs.
The first thing you have to find out is if this is the tool you are looking for.
For generating PDFs from scratch tools like [gofpdf](https://github.com/jung-kurt/gofpdf) may better suited for your needs.

If you could go into more details about your usecase I would be in a better position to help you decide if this is something pdfcpu can help you with.

You mention adding *links*. 
What do you mean by that?

Right now pdfcpu does not offer a command for adding link annotations but it really depends on what you mean by links.

As far as getting a PNG image on a PDF page..
There are at least two ways pdfcpu can help you placing an image on a PDF page:

1) import and stamp
You can import an image onto a new blank page using the `pdfcpu import` command or the corresponding api call. You can also specify a position, a scale factor or image dimensions and the desired dpi. After this step you can repeatedly add more page content by using the `pdfcpu stamp add` command or its corresponding api call.

2) stamp
If you have a pdf with already existing content you could use the `pdfcpu stamp add` command or its corresponding api call.

Right now you find the docs and examples for the stamp command [here](https://pdfcpu.io/core/stamp) and for the import command [here](https://pdfcpu.io/generate/import).

`pdfcpu help stamp` and `pdfcpu help import` also have a lot of valueable information.

.. and there is also the GoDoc for the pdfcpu API [here](https://godoc.org/github.com/pdfcpu/pdfcpu/pkg/api)

When you say you wish there was a quickstart tutorial would it be sufficient to explain pdfcpu's command set on the comandline? Because that's something I am working on.
The API just mirrors all CLI commands so I think this will help for starters.

Explaining the API better amounts more to a quickstart project on Github 
but I don't know where I get the time for something like this.

Let me know what you are missing in the docs and I can fill in the blanks.
Like I said I could be of better help if you have more details about your usecase.

Thanks for using pdfcpu 💚

**Comment by mpup371** [comment]
Hi Horst,
thanks to take time to answer.
I was not enough clear on my use case: my goal was to add annotations for
external urls, and an image on a existing page.
(on an existing pdf document with only one page).
Actually the stamp is what I need for the image, I didn't notice It.
I created a link based on you example file (more specifically
createLinkAnnotationWithRemoteGoToAction).
But to be more generalist, my idea  was not to use the command line tool or
the API for pre-defined actions like "stamp".
I was more on the idea to use the underneath code ("
github.com/pdfcpu/pdfcpu/pkg/pdfcpu") as a general library to manipulate
pdf objects in my own code.
Your code is what I found the closest to that. But when I saw private
functions, I understood they was not meant to be used by others, so not
documented.
I don't know if it is your intention, but I think it would be a great idea
for the open-source community.
Hope it is more clear now :-)

regards
jf


Le jeu. 10 oct. 2019 à 14:41, Horst Rutter <notifications@github.com> a
écrit :

**Comment by hhrutter** [comment]
`createTestPDF.go` and most of the code it calls is highly experimental.
It is part of trying to find a simple way for generating PDFs.
I am glad you have some use for it.

Play around and let me know if you have any suggestions for extending the api.
It's just that I don't have the time to add a universal add annotation functionality because
there are around 20 different annotation types.

**Comment by hhrutter** [comment]
[v0.3.12](https://github.com/pdfcpu/pdfcpu/releases/tag/v0.3.12) lets you add link annotations via the API and create stamps with link(annotation)s via the API and the CLI.
