### ISSUE TITLE
PDF Form exporting

### ISSUE THREAD

**Issue by cmeans** [pdfcpu/pdfcpu#124]
I see that you do have Filling out AcroForms on your list for future features, but what about exporting the data for already filled-out forms?

I'm looking for an easy way to export form data into a JSON or XML structure via Go.  Your package seems to be quite close to what I need, but doesn't appear to already have that function.

**Comment by hhrutter** [comment]
Hey, thanks - interesting use case.
Defnitely doable, I put that in the pipeline.

**Comment by StefanSchroeder** [comment]
+1

**Comment by raff** [comment]
This is a quick & dirty way to get form values. You'll need to deal with the value types (i.e. boolean for buttons, string for text, and I didn't look at other types yet).

`
// +build ignore
package main

import (
	"fmt"
	"log"
	"os"

	"github.com/pdfcpu/pdfcpu/pkg/api"
	"github.com/pdfcpu/pdfcpu/pkg/pdfcpu"
)

func main() {
	source := os.Args[1]

	ctx, err := api.ReadContextFile(source)
	if err != nil {
		log.Fatal(err)
	}

	cat, err := ctx.Catalog()
	if err != nil {
		log.Fatal(err)
	}

	acroform, ok := cat.Find("AcroForm")
	if !ok {
		log.Fatalf("No forms for %v", source)
	}

	adict, err := ctx.DereferenceDict(acroform)
	if err != nil {
		log.Fatal(err)
	}

	fields := adict.ArrayEntry("Fields")

	for i, o := range fields {
		ir := o.(pdfcpu.IndirectRef)
		e, ok := ctx.FindTableEntryForIndRef(&ir)
		if !ok {
			log.Fatalf("No XrefTableEntry for %v", ir)
		}

		d, ok := e.Object.(pdfcpu.Dict)
		if !ok {
			log.Fatalf("Object %v is not a Dict", ir)
		}

		v := d.StringEntry("T")
		if v == nil {
			log.Println("No field name for field %v", i)
		}

		fieldName := *v

		v = d.NameEntry("FT")
		if v == nil {
			log.Println("No field type for field %v %v", i, fieldName)
		}

		fieldType := *v

		fieldValue, _ := d.Find("V")
		fmt.Printf("%v %v %v\n", fieldName, fieldType, fieldValue)
	}
}
`

**Comment by StefanSchroeder** [comment]
This does the trick. Thank you very much.

**Comment by hhrutter** [comment]
Hello!

AcroForm processing is subtle in nature and  I see two operations each being the inverse of the other, form filling and form extraction. My intention is to implement both in one go so we get a consistent api, which - since you are asking - isn't yet fleshed out. 
My focus and I am really busy with that is still better font support after that I am going to tackle form processing.

**Comment by StefanSchroeder** [comment]
I want to extend the example above to actually print out JSON using the template-engine. I only need to figure out how to define the structs that are inserted into the template from the forms in a generic way, since you cannot know what fields you are going to find in the PDF in advance. Anyway, I am looking forward to the form extraction being implemented at some point. Thanks in advance.

**Comment by kpym** [comment]
> My intention is to implement both in one go so we get a consistent api, which - since you are asking - isn't yet fleshed out.

I agree that export and import should go together. It will be nice if the cli interface could export to/import from `json` as requested before. 

In this way we can : 
1) export the "empty" form as json.
2) fill the json with our data.
3) import the filled json.

**Comment by StefanSchroeder** [comment]
Any progress on this issue? QPdf actually does support JSON export. https://qpdf.readthedocs.io/en/stable/cli.html#json-options 
Being compatible would be a way to not reinvent the wheel.

**Comment by hhrutter** [comment]
A little bit tricky, but right on track..
Stay tuned for the next release.
Thank you!

**Comment by hhrutter** [comment]
=> https://github.com/pdfcpu/pdfcpu/releases/tag/v0.4.0
