### ISSUE TITLE
Error validating PDF file: problem dereferencing stream

### ISSUE THREAD

**Issue by lynzt** [pdfcpu/pdfcpu#151]
Running: `pdfcpu validate` produces the following error...

[crash - 3f41e7e3.log](https://github.com/pdfcpu/pdfcpu/files/4017236/crash.-.3f41e7e3.log)

We're unable to provide the original file as it contains personal information. Please let me know if you have what you need to recreate (and fix) the issue.

**Comment by hhrutter** [comment]
Hi!

Please scroll down on the README.md to *Reporting Crashes* and follow up.
The minimum I need for triaging is very verbose log output.
Thank you for using pdfcpu 💚

**Comment by lynzt** [comment]
Hi,

Oops, with all my file validating, I must have removed the -vv flag for this run. Here is the longer report. Thanks for all your work 💙 

[crash - 3f41e7e3.log](https://github.com/pdfcpu/pdfcpu/files/4019333/crash.-.3f41e7e3.log)

**Comment by hhrutter** [comment]
I am seeing a premature EOF encountered.
Assuming this was created by Adobe and you can open it with both Adobe Reader and Mac Preview
this looks strange to me. Seems like a cut off stream object.

There is also an unusual trailerDict:
<< /Size 10 /Root 5 0 R /Info 6 0 R /Info 7 0 R /Info 8 0 R /Info 9 0 R >>

In order to find out more I'd need the file.
You can also send an email to hhrutter@gmail.com
Maybe there is a way to anonymize the data.

**Comment by lynzt** [comment]
Thanks for the info. I will check if we can anonymize the data on our end. I'll let you know either way.
Thanks again!

**Comment by lynzt** [comment]
We were able to re-export the pdf which fixed the validation problem on our end... so closing this issue.
Thanks...

**Comment by ljyf5593** [comment]
i have the seem problem  and this is my crash.log
[crash.log](https://github.com/pdfcpu/pdfcpu/files/4336441/crash.log) and i can send you the pdf file to your email please help me

**Comment by hhrutter** [comment]
Thank you.
I will have a look.
