### ISSUE TITLE
Hexadecimal String parse error

### ISSUE THREAD

**Issue by AlmogBaku** [pdfcpu/pdfcpu#155]
I cannot decrypt a file encoded with [mpdf](https://mpdf.github.io/reference/mpdf-functions/setprotection.html):

```go
	err := api.DecryptFile("form.pdf", "unenc.pdf", pdf.NewRC4Configuration("mypass", "", 40))
	if err != nil {
		panic(err)
	}
```
throws an error:
```
panic: dereferenceObject: problem dereferencing object 10: pdfcpu: parse: corrupt hex literal
```

I simply encrypted the file using mpdf as described here https://mpdf.github.io/reference/mpdf-functions/setprotection.html:
```php
$pdf->SetProtection(['print'], "mypass")
```

qpdf decrypt it successfully.

**Comment by hhrutter** [comment]
Hi!

Can you share an encrypted test PDF so I can analyze this?
Thank you!

**Comment by AlmogBaku** [comment]
[test2.pdf](https://github.com/pdfcpu/pdfcpu/files/4025828/test2.pdf)
password: 1234
```go
err := api.DecryptFile("test2.pdf", "unenc.pdf", pdf.NewRC4Configuration("1234", "", 40))
if err != nil {
  panic(err)
}```

generate code:
```php
#!/usr/bin/php
<?php
require_once __DIR__ . '/vendor/autoload.php';
if (php_sapi_name() !== 'cli') {
    exit;
}

use FOS\RestBundle\Request\ParamFetcherInterface;
use Mpdf\Mpdf;
use Mpdf\Output\Destination;

$mpdf = new Mpdf();

$mpdf->WriteHTML('Hello World');
$mpdf->SetProtection(['print'], "1234");
$mpdf->Output("test2.pdf", Destination::INLINE);
```

**Comment by AlmogBaku** [comment]
I don't know if that helps, but it seems like the problem is that there are spaces in the file. You can see the excerpt I took into the playground while trying to debug (https://play.golang.org/p/kUhi2ELA7Jj)

I just left it there since I have no idea what the protocol says and how should one use it :O

**Comment by AlmogBaku** [comment]
hmm... it seems it's also can't read not-encrypted files that contains the Panose entries
 (https://online.flippingbook.com/view/415756/461)

see the not-encrypted file here:
[test2unenc.pdf](https://github.com/pdfcpu/pdfcpu/files/4032310/test2unenc.pdf)

**Comment by hhrutter** [comment]
This definitely helped!
Thanks!

The hexadecimal string parser does not accept whitespace within the string.
This is a bug and I will push this asap.

On a sidenote the *Panose* hexstring appearing in this PDF is invalid.

Instead of:
 `/Panose < 0 0 2 6 6 6 5 6 5 2 2 4 >`

it should really be:
`/Panose <00 00 02 06 06 06 05 06 05 02 02 04>`
like it is laid out in the PDF spec.

The PDF spec defines under 7.3.4.3 Hexadecimal Strings:
```
Each pair of hexadecimal digits defines one byte of the string. 
White-space characters (such as SPACE (20h), HORIZONTAL TAB (09h), CARRIAGE RETURN (0Dh), LINE FEED (0Ah), and FORM FEED (0Ch)) shall be ignored.
If the final digit of a hexadecimal string is missing—that is, if there is an odd number of digits—the final digit shall be assumed to be 0.
```

And that's why the PDF Hexstring parser turns:
`< 0 0 2 6 6 6 5 6 5 2 2 4 >`
into
`000020606060506050202040`
when it really should be:
`000002060606050605020204`
See also [here](https://en.wikipedia.org/wiki/PANOSE).

I am leaving this with the corrected parsing. 
This (invalid but semantically correct FontDescriptor attribute) is a good example of a situation that's obvious but hard to fix w/o any magic.

**Comment by AlmogBaku** [comment]
wow! amazing!!
That was super fast! and it work great with my use-case (and the real world, production-grade use-case)

Thanks
