### ISSUE TITLE
Visual PDF diff

### ISSUE THREAD

**Issue by kpym** [pdfcpu/pdfcpu#163]
It exists already [diff-pdf](https://github.com/vslavik/diff-pdf), but it is not a single executable. 
It takes two pdfs and superpose the pages by applying some color filters.

Is it possible to realize the same thing with `pdfcpu` ? If not, is it possible to add this feature ?
And in both cases having `-diff` flag will be nice.

Thanks for your fantastic software.

**Comment by hhrutter** [comment]
Interesting use case!

pdfcpu does not offer such a command but using a pdf stamp it generates out.pdf overlaying a.pdf with b.pdf. You can play around with the opacity of the pdf stamp in order to visually make out any differences, like so:

`pdfcpu stamp add -mode pdf b.pdf 'pos:bl, scale:1.0 rel, op:.5' a.pdf out.pdf`

**Comment by kpym** [comment]
When I try this I get `pdfcpu: indRefToObject: input argument is free obj`, which is a little bit cryptographic error for me.

Playing only with transparency is possible, but is not as good as making the two pdfs "complementary " in color. From time to time the différences are very small.
Does the PDF format allows something like "color filters" ?

**Comment by hhrutter** [comment]
This is the first use case for something like *color filters* so this looks like a new feature.

Other than that, I believe the above sounds like a bug.
Please make sure both your files validate ok using `pdfcpu val in.pdf &> out.log`
if you get an error then repeat using -vv: `pdfcpu val -vv in.pdf &> out.log
If the file validates ok and you only get an error during your specific pdfcpu operation,
then just rerun your command adding -vv 

Thank you for using pdfcpu

**Comment by hhrutter** [comment]
diff-pdf comes with its own viewer and highlighting visual differences involves pixel manipulation. 
Although is seems useful I highly doubt this functionality has anything to do with PDF per se.

I think pdfcpu is far from being able to provide such a feature because it does not come with its own viewer.

On the other hand if there was a pdfcpu viewer this would be something worth implementing with reasonable efforts.

**Comment by kpym** [comment]
`diff-pdf --output-diff diff.pdf file1.pdf file2.pdf` produce the `diff.pdf` from `file1.pdf` and `file2.pdf`. I was talking about this feature. The viewer is out of scope here for me. I think that `pdfcpu` should stay a small cli tool that do well what it is supposed to do and let the pdf view to the viewers.

I have checked and you are right `diff-pdf` works on a pixel level. This is why the produced diff (collection of images) is really bigger than the originals. This is a bad news. I was hoping that there is a feature in the PDF specification that allows to apply a color filter to an object.

If the PDF specification do not allows this kind of manipulation without converting to images, may be it is possible to superpose `file1` then a "uniform color image1" (for example 1x1 image scaled to cover the  entire page) with certain opacity, then `file2` and then "complementary uniform color image2". And playing with opacity and grouping to produce a pdf that visually is the same as `file1` if `file1=file2`. 

As I do not know much about PDF I don't know if what I'm proposing is doable. Sorry.

**Comment by hhrutter** [comment]
Sorry that's out of scope because we do not have rasterization as of now.

**Comment by kpym** [comment]
You shouldn't be sorry. `pdfcpu` should remain a tool for handling pdf objects. There are already quite a few rasterization/visualization software that can do that. 

Keep it simple, and thanks for considéring my request ;)
