### ISSUE TITLE
watermark: CJKV font support

### ISSUE THREAD

**Issue by xzyan** [pdfcpu/pdfcpu#171]
#  Chinese garbled

```go
pdfcpu.ParseTextWatermarkDetails("测试", "s:.8, m:0, c:.9 .0 .0, op:.5")
```

**Comment by hhrutter** [comment]
Hello!

This is because the default font is Helvetica, one of the PDF core fonts
and this Type1 font does not provide chinese glyphs.

Generally you can also use any TrueType font if you install it like so:
`pdfcpu font install myfont.ttf`

And you can list all pdfcpu fonts anytime using:
`pdfcpu font list`

Unfortunately right now, pdfcpu only supports WinAnsi/Latin encoding for fonts,
BUT I am working on asian font support right now.

You could really help me if you could tell me which font(s)
you would like to use then I will extend pdfcpu to support it.

Some more questions:

* Are you using simple or traditional chinese fonts?

* Which encoding are you using on yout command line?

* Is it a Win, Mac or Linux command line?

Oh, and thank you so much for using pdfcpu 💚

**Comment by xzyan** [comment]
Thank you for your answer

**Comment by xzyan** [comment]
Thank you for your answer

**Comment by wxj95** [comment]
hello! @hhrutter 
Thx for this great pdfcpu,it's helpful to me.
And I want to add simple chinese watermark, such as simsun.ttf... but it not support.
So How can I solve it.

**Comment by hhrutter** [comment]
Hello!

Support for asian fonts is a feature we are working on!
Please check back.

Thank you for using pdfcpu 💚

**Comment by wxj95** [comment]
Hello!
Thx for your response！
And I am looking forward to it.

**Comment by m31527** [comment]
Thanks for great source code and I would like to add Traditional Chinese watermark , so could you support in future?

**Comment by hhrutter** [comment]
Yes! I am hoping to get CJKV support into the next release.
Thank you for using pdfcpu 💚

**Comment by HorizonChM** [comment]
> 
> # Chinese garbled
> 
> ```go
> pdfcpu.ParseTextWatermarkDetails("测试", "s:.8, m:0, c:.9 .0 .0, op:.5")
> ```

暂时还不支持中文，可以先生成文字图片，再加图片水印，算是曲线救国了(*￣∇￣*) 
In English：Because Chinese is not yet supported, we can generate picture(contain our text) first, and then add this picture as image watermark.

**Comment by hhrutter** [comment]
CJKV fonts are supported starting v0.3.7
