### ISSUE TITLE
Update examples

### ISSUE THREAD

**Issue by wxj95** [pdfcpu/pdfcpu#193]
![image](https://user-images.githubusercontent.com/23724009/83124226-81efad00-a108-11ea-9782-8e536f03c97f.png)
![image](https://user-images.githubusercontent.com/23724009/83124236-84ea9d80-a108-11ea-85b6-3cb03897f6e7.png)

ExampleAddWatermarksFile
```
onTop = true
wm, _ = pdfcpu.ParsePDFWatermarkDetails("stamp.pdf:2", "s:.5 a, d:2", onTop)
AddWatermarksFile("in.pdf", "", nil, wm, nil)
```
the example for AddWatermarksFile doesn't modify，it will return `ambiguous parameter prefix "s"`
And can you give a explain list for the parm's ?

Thx for your great project!

**Comment by hhrutter** [comment]
Hello!
Thanks for reporting this!

😞 I need to update the examples.

Generally, you can use any unique abbreviation for all parameters in the watermark description:

So for example:

 "d" is the same like "dia" is the same like "diagonal" or
"op" is the same like "opacity" but
"o" is ambiguous because there are 2 parameters starting with "o": "offset" and "opacity".

Since v0.3.3 introduced "strokeColor", "s" which used to be unique for "scaleFactor" is now ambiguous. 

Short answer:
 Use: "sc" or "scalefactor" for all instances in the examples where "s" is used
and "ma" for all instances where "m" is used because now we have "margins" on top of "mode" which is a synonym for "renderMode".

Don't forget to check out [the documentation for stamping with pdfcpu](https://pdfcpu.io/core/stamp).
