### ISSUE TITLE
PDF crop support

### ISSUE THREAD

**Issue by chanhee** [pdfcpu/pdfcpu#210]
I would like to have a function to crop the size of PDF page.
like cpdf... (top bottom left right) or another way
cpdf -crop "20mm 20mm 15mm 15mm" in.pdf -o out.pdf

in.pdf  200mm x 300mm
out.pdf  170mm x 260mm

**Comment by hhrutter** [comment]
OK, this sounds like a useful feature!

**Comment by kpym** [comment]
I also want to advocate for this feature. Now that pdfcpu has decent support of the cropbox (#245) may be it will be not so hard just to manipulate it.

**Comment by kpym** [comment]
I do not agree with the proposed interface `--crop (top bottom left right)`. I think that there should be two interfaces: 
- `--crop "minX minY maxX maxY"` in default units as is the internal `\cropbox`
- `--margins "top [right [bottom [left]]]]"` as in `css` where the values have units and could be even negative (to increase the visible part). It will be nice if we can use the same defaults as in [css](https://developer.mozilla.org/en-US/docs/Web/CSS/margin). So for example if we set `--margins "1in 2cm"` this should be the same as `--margins "1in 2cm 1in 2cm"` and so on.

In any case if the resulting `cropbox` is bigger than the `mediabox`, the `mediabox` should be adjusted as well to keep the `cropbox` inside the `mediabox`.

**Comment by hhrutter** [comment]
The spec says the crop box defines a mediabox region to which the contents of the page shall be clipped (cropped) when displayed or printed. As a result I do not see a requirement where the mediabox needs to adjust to the cropbox.

I am free to define a cropbox any way I like and need to live with the consequence which is the PDF viewer simply renders the portion of the cropbox that stays within the mediabox.

I agree it makes sense to both allow setting the cropbox absolute as well as relative to the containing mediabox as in: 

```
pdfcpu crop abs xmin ymin xmax ymax in.pdf out.pdf

pdfcpu crop rel top right bottom left in.pdf out.pdf 
```

**Comment by kpym** [comment]
> The spec says the crop box defines a mediabox region to which the contents of the page shall be clipped (cropped) when displayed or printed. As a result I do not see a requirement where the mediabox needs to adjust to the cropbox.
> 
> I am free to define a cropbox any way I like and need to live with the consequence which is the PDF viewer simply renders the portion of the cropbox that stays within the mediabox.

I don't know if this is in the specifications, but the `cropbox` (as all other boxes) should be inside the `mediabox`. In my experience the viewers "normalize" the cropbox by intersecting it with the mediabox.
So if you want to enlarge the cropbox, you may need to enlarge the media box too, if you don't do this the enlargement may have no (or only partial) effect.


> I agree it makes sense to both allow setting the cropbox absolute as well as relative to the containing mediabox as in:
> 
> ```
> pdfcpu crop abs xmin ymin xmax ymax in.pdf out.pdf
> 
> pdfcpu crop rel top right bottom left in.pdf out.pdf 
> ```

It will be nice if we can use less than four numbers for the margins because very often they are the same. For example 

```shell
> pdfcpu crop rel 1cm in.pdf out.pdf
```
could be useful.

Another suggestion : may be allowing `%` could be also useful. For example 

```shell
> pdfcpu crop rel 0% 50% 50% 0% in.pdf out.pdf
```
will display only the top-left quarter of the page.

**Comment by kpym** [comment]
> As a result I do not see a requirement where the mediabox needs to adjust to the cropbox.

@hhrutter I found this in the PDF specifications (v1.5):
> The crop, bleed, trim and art boxes should not ordinary extend beyound the boundaries of the mediabox; if they do, they will be effectively reduced to their intersection with the media box.

**Comment by hhrutter** [comment]
Exactly my point 👍

**Comment by kpym** [comment]
> Exactly my point 👍

Not exactly, I think. You have to adjust the `mediabox` if you want the result of `cropbox` enlargement to be visible. Else the user that enlarge the `cropbox` will not understand why nothing changes after  
```
> pdfcpu crop rel -1cm in.pdf out.pdf
```
(if for example the `cropbox` was missing or equal to the `mediabox` before the command, which is very often the case)

**Comment by hhrutter** [comment]
I think the whole point of the spec is "Don't touch the mediabox".

This also makes sense, because usually that's your paper size for printing.
If my paper size is A4 because that's what I am using for printing why would I enlarge the mediaBox?

**Comment by kpym** [comment]
> I think the whole point of the spec is "Don't touch the mediabox".

I don't think so.

> This also makes sense, because usually that's your paper size for printing.
> If my paper size is A4 because that's what I am using for printing why would I enlarge the mediaBox?

The reason to want to change the `mediabox` is the same as almost everything in `pdfcpu` : because the creator of some pdf is not the user of this pdf in general, and the user may want to use the pdf in a different way than the creator has decided. And we can add to this that very often the pdf creators are not pdf specialists ;)

Let's take the example of a pdf that contains some drawing without margins that is not meant to be printed directly but to be incorporated in other documents. And if we decide that we want that this drawing should always be protected by 1in margin, we would like to increase the "paper size" to add this extra margins.

I can give you another example : when I have to incorporate pages with "Letter" size in "A4" document I would like to change the "paper size" of this documents by just adjusting the margins (because the two formats are close enough to make this possible).

**Comment by hhrutter** [comment]
I understand that somebody wants to adjust page boundaries for some reason.
We can extend the api in order to make this happen, I am not so sure if this is something expected from a cli.
I am against cli magic in general and automagically enlarging the containing media box in this specific scenario but we may provide a flag for such a behavior on the corresponding api call on a use-at-your-own-risk basis.

About your example:
`> pdfcpu crop rel -1cm in.pdf out.pdf`

I understand what it is you are trying to achieve but I am against negative values for cropping because it goes against what cropping means - defining a contained rectangular region.

What you really want is:
1) Enlarge the mediabox
2) Define a desired crop box

I will need to think more about this but I really want to keep the cli as simple as possible.

**Comment by kpym** [comment]
@hhrutter some additional arguments :

- `cpdf` and `pdfcrop` allow negative values (as the PDF specification allows) for boxes (absolute and relative) coordinates.
- in `cpdf` we can manage all boxes with `cpdf -mediabox "<box coordinates>"`, `cpdf -cropbox "<box coordinates>"` and so on.
- Not alowing negative coordinates do not avoid the "box intersection" normalisation. For example, if a user call 

```shell
> pdfcpu crop abs 0 0 400 400 
```

to set only `/CropBox [0 0 400 400]` on pdf that has `/MediaBox [50 50 350 350]`, the user will see no effect of this command. 

IMO, after thinking about it, there are two type of users
- 99% of the users do not know about the existance of the five type of boxes and they just want to change the size of the page that they see/print. The command `pdfcpu crop` should be made for them and this command should set all the four boxes (`mediabox`, `bleedbox`, `trimbox` and `cropbox`, except the `artbox`) at the same time to the desired coordinates (and negative coordinates should be allowed to enlarge pages).
- 1% of the users know about the five type of boxes and they know about the inheritance, about the normalisation, about the usage and so on. For this kind of power users it will be nice to have `pdfcpu box` with `list`, `set` and `delete`.

Thanks for considering this questions.
