### ISSUE TITLE
api: Revisit init() in font pkg

### ISSUE THREAD

**Issue by edwinmo-splunk** [pdfcpu/pdfcpu#225]
Hey everyone! First of all, kudos on a great library! I've been looking for a good pdf library for trimming pdfs and stumbled upon this one. It looks great so far!

The process that will be using the library is under increased security measures. In our containerized environment, we specifically removed the ability for our Golang process to write any files into the filesystem. After playing around with the lib and successfully `Trim`ing, I ran into this error:

```
Failed access to font dir: mkdir /nonexistent: permission denied
```

It looks like the `metrics.go` file in the `font` pkg is attempting to create a file:

```Golang
func init() {
	//fmt.Println("metrics.init begin")
	dir, err := Dir()
	if err != nil {
		fmt.Fprintf(os.Stderr, "Failed access to font dir: %v\n", err)
		os.Exit(1)
	}
        ...
```

As I mentioned, we specifically don't want this Golang process to be mucking with the filesystem. I was able to get around this by commenting out the `init` function. The `init` function leaves very little flexibility in where and what scenarios we want it to run. In my case, it's not necessary to run. The import chain is:

```
"github.com/pdfcpu/pdfcpu/pkg/api" trim.go
    imports 	"github.com/pdfcpu/pdfcpu/pkg/pdfcpu" create.go & stamp.go
             imports 	"github.com/pdfcpu/pdfcpu/pkg/font" metrics.go
```

Can we revisit this `init` function? It doesn't seem like the entire pkg needs to be `init`'d, at least in my use case, so maybe some lazy initialization would be more appropriate?

I'd like to avoid one-off vendored changes or forking. If there's a better way of handling this that I did not spot, please let me know. Appreciate the help!

-Edwin

**Comment by hhrutter** [comment]
Hello!

Right now the only reason pdfcpu needs a config dir is for installing fonts for stamping/watermarking.
I understand if you don't care about watermarking PDFs you couldn't care less about the config dir or any loading of fonts during `init()`.

We could get rid of  ` init()` and only load fonts for pdfcpu operations that need font support but the real issue here is that eventually there will be a concrete pdfcpu config dir and a way to customize it via api and cli so we can't just ignore a missing config dir in the long run.

Please check #186. Maybe this helps.

**Comment by edwinmo-splunk** [comment]
Hey @hhrutter! Thanks for the quick reply. Your reasoning makes sense to me. I'll set `$HOME` to `/tmp` for the time being. A more first-class approach for the config dir would be nice, and I see that's on your radar so that's great. Thanks again!
