### ISSUE TITLE
Extract pages into a list of []bytes.Buffer

### ISSUE THREAD

**Issue by saucesaft** [pdfcpu/pdfcpu#226]
Hello, first of all, this a trully awesome library, thanks for it.

I've seen that there's a extractPages and also a extractPagesFile function. But both of them output to a directory, is it possible to make extractPages output a list of bytes.Buffer instead of actually writing the file?

My usecase would be to extract all the pages, edit each page individually and then merge them in a specific order, all by processing the io.ReadSeeker and writing the file just at the end.

**Comment by saucesaft** [comment]
Update: I've found the "trim" method which does exactly what i want but i'll need to loop trough each page, since it'll output a single io.Writer. So i could call trim for every page, but it could be even more convenient to use ExtractPages without looping the pdf pages.

**Comment by hhrutter** [comment]
Hi!

It's all there and ready to use:

Check out:
* [the v0.3.5 release notes](https://github.com/pdfcpu/pdfcpu/releases).
* [pkg/api/test/extract_test.go](https://github.com/pdfcpu/pdfcpu/blob/master/pkg/api/test/extract_test.go): func TestExtractPagesLowLevel

Thanks for using pdfcpu 💚

**Comment by hhrutter** [comment]
Can you tell me what do you mean by "editing"?

Maybe what you really looking for is in: 
[pkg/api/test/extract_test.go](https://github.com/pdfcpu/pdfcpu/blob/master/pkg/api/test/extract_test.go): func TestExtractContentLowLevel(t *testing.T)

**Comment by saucesaft** [comment]
All righ i see, i see. I opened this issue since both ExtractPage and ExtractPageFiles take an "filename string" as output. I expected to ExtractPage to take an []io.Writer as an output. But your suggestion seems viable.
So now with the context, is it possible to get the io.Writer of the page with the context struct?

Also, by editing i meant this:
- Grab a pdf file
- Get the io.Writer for each page
- Add stamps / text / rotate for each page individually
- Finally merge each page and write it to a file

**Comment by hhrutter** [comment]
I understand you want to stamp and rotate pages but what do you mean by *add text*?

You can't just get an io.Writer for a page in order to add stamps and apply rotation.
Applying a stamp on a page involves more than content stream manipulation and the rotation is applied to the corrersponding page dictionary.

Right now pdfcpu does not support adding arbitrary page content directly but you can add a text based stamp for a set of pages. If this is what you want and only if you are able to process all pages AND want to apply the same stamp and rotation, right now the easiest way would be to first stamp all pages in one call and then rotate all pages in another call. This way you can skip merging.

Could you please go into a bit more detail explaining your usecase?
I think I need a better understanding of what you are trying to achieve in order to support you.

**Comment by saucesaft** [comment]
Alright sorry, let me explain.
Im creating a GUI pdf editor with go, regarding the "backend" or "pdf editing side" im using this excellent library so that my gui can use it, im writing an small abstracted wrapper so that i can easily modify the pdf's.
In the GUI application, the user has the ability to change the page order, and also select a page and stamp it with images or text.
In order to do this, i came up to "extract" each page of the pdf as if it were a page-only pdf using the Trim. So that i could have an array of a buffer representation of each page. So that after the user in the gui decides the modifications/stamps to be applied, they are applied to each individual page (since each page is not going to have the same modifications).

So that's why my original question was if there was a method that could read a pdf file and return an array of buffers with each pdf page inside of it.

Thanks for helping btw :)

**Comment by hhrutter** [comment]
Understood.

Unfortunately pdfcpu's api is not in the shape that I would like it to be. It's ongoing work, but issues like yours raise real world requirements so that's good and will be helpful in making progress on that front.

Right now I can only offer a hack.. take the following pseudo code as an inspiration:

```
ctx, err := api.ReadContextFile(inFile)
inFiles := []string{}
for each page {
    ctxNew, err := ctx.ExtractPage(each)
    selectedPages := pdfcpu.IntSet{1}
    pdfcpu.RotatePages(ctxNew, selectedPages}, rotation)
    wm, err := TextWatermark(text, desc, onTop, false)
    pdfcpu.AddWatermarks(ctxNew, selectedPages, wm)
    inFiles = append(inFiles, tmpFileForEachPage)
    f, err := os.Create(tmpFileForEachPage)
   api.WriteContext(ctxNew, f)
}
api.MergeCreateFile(inFiles, outFile, nil)
```

I will see if I can make code available on pdfcpu.Context to make all of this easier.

**Comment by saucesaft** [comment]
Don't worry, think I got an idea of how to implement this. I'll upload a gist in a moment. Thanks anyway :)

**Comment by saucesaft** [comment]
https://gist.github.com/saucesaft/363f55a6e4cea672d83c09e3f2efadc0

Here's my somewhat hacky solution on how to split the file into different pages, edit each one individually and merge them into a new file. (To test it you need a pdf of 2 pages) Thanks!

P.D. If i have another question regarding this library but from another topic should i make another issue?

**Comment by hhrutter** [comment]
Yes open another issue or post your question on the #pdfcpu channel in the Gopher Slack.
