### ISSUE TITLE
api: Provide a more flexible way to apply stamps to selected pages in one go

### ISSUE THREAD

**Issue by meerkat-mary** [pdfcpu/pdfcpu#236]
Hey pdfcpu developers

I’ve been using your excellent code to produce some pdf reports that my customers can download, I’ve been using the merge tool to combine their documents successfully 😄 

I feel it would be great to add page numbers to the final document, starting from page 1 and I’d like to get some advice on how I can do that please. I’ve been using the API that pdfcpu offers and I think the stamp tool could be used to stamp each page with a different watermark (for each page number) however I am trying to find a more efficient way to do so:

- I tried using the AddWaterMarksFile function, however it took a really long time to add the page numbers, since a lot of my documents can go up to 500 pages

- Instead of passing in an os.File as the input and output files, I passed in a Reader and bytes.Buffer (and then passed in a reader of the generated bytes into the next iteration), this was a bit better but it still took around 1 second per page since I think it was reading from the start of the file each time in the io.ReadSeeker? so for 500 pages they’ll be waiting for a while to get their pdf :(
- I looked into the multi-stamp feature, it looks like that’s not available via the API?

Would it be possible to update the API to allow me to pass in a map of watermarks perhaps? (As I may need to add Roman numerals for some page numbers) With the key being the page number, and the value being the unique watermark - and then the library functions can efficiently apply each watermark as it reads through the input PDF? 

Or alternatively, if there is a way to get this done with the existing library functions, could you kindly provide a code example?

(Sorry if I've posted this in the wrong section, I'm new to the website)

Grateful for your time! 
Mary

**Comment by hhrutter** [comment]
Hi there!

Is your usecase merging a couple of multipage PDFs and then applying consistent page numbering to the result?
If this is what you want, then stamping should be the right tool, since that keeps you in control of font, design and the position on the page.

Multi-stamping a PDF with the corresponding pages of another PDF is supported via`AddPDFWatermarksFile`.
Have a look at https://github.com/pdfcpu/pdfcpu/blob/master/pkg/api/test/stamp_test.go
I don't think that will help you in your scenario though. You would have to prepare a template PDF with page numbers applied to empty pages everytime you need to stamp a merged file. Also since you said on some pages you may want to use a different numbering scheme..

But this is definitely doable:

1) Populate a `map[int]*pdfcpu.Watermark` by looping over `api.TextWatermark`.
The keys of this map comprise the page numbers of all pages that should be watermarked (with the Watermark referenced by the value for a specific key).

2) Then you pass this into smth like:
`api.AddFlexWatermarksFile(inFile, outFile string, wmarks map[int]*pdfcpu.Watermark, conf *pdfcpu.Configuration) (err error)`

which doesn't exist yet of course..

.. but I think this would be a useful extension since it adds a lot of flexibility for stamping.
Like this I can supply a mix of text, image and even PDF watermarks to corresponding pages in one pass.
Maybe this should really be the glue between the api and the pdfcpu layer below.

Should be available in one of the next releases.

Thank you for using pdfcpu 💚

**Comment by meerkat-mary** [comment]
Awesome! thank you so much @hhrutter !

**Comment by hhrutter** [comment]
This feature is now available with the latest commit.

**Comment by meerkat-mary** [comment]
Thank you @hhrutter - I really appreciate it!

**Comment by meerkat-mary** [comment]
Hey @hhrutter - just wanted to let you know that your change works flawlessly, I'm able to add page numbers in milliseconds now, you are a star! 🌟

**Comment by hhrutter** [comment]
Glad to hear you're havin fun with pdfcpu 💚 
Please spread the word and maybe consider sponsoring me on Github
