### ISSUE TITLE
attachments: id vs. description

### ISSUE THREAD

**Issue by sagikazarmark** [pdfcpu/pdfcpu#249]
I noticed a strange behavior in "attachment ID" naming when parsing a PDF file not created by pdfcpu itself.

Basically, the attachment ID and the file name (called ID in the `Attachment` struct) might not be the same. As a result, the attachments returned by `ListAttachments` cannot be used to filter attachments in `ExtractAttachments`.

I'm not sure if this is on purpose or by accident. By the looks of it, one can use the `ExtractAttachments` call without IDs and filter the attachments manually, but I guess that would have some sort of performance penalty.

Here a failing test case:

```go
func TestExtractAttachmentID(t *testing.T) {
	file, err := os.Open("testdata/test.pdf")
	require.NoError(t, err)

	ctx, err := ReadValidateAndOptimize(file, nil)
	require.NoError(t, err)

	attachments, err := ctx.ListAttachments()
	require.NoError(t, err)

	attachmentIDs := make([]string, 0, len(attachments))

	for _, attachment := range attachments {
		attachmentIDs = append(attachmentIDs, attachment.ID)
	}

	extractedAttachments, err := ctx.ExtractAttachments(attachmentIDs)
	require.NoError(t, err)

	assert.Equal(t, len(attachments), len(extractedAttachments))
}

```

@hhrutter you can use the same PDF I've sent you for #244

**Comment by hhrutter** [comment]
I am assuming you are using the latest commit.
OK, I take a look.

**Comment by hhrutter** [comment]
The reason for this behavior is that the PDFWriter that was used to create this file stores the file attachment in the Nametree using the description as the id. I haven't seen that many files with attachments, but this does not make much sense to me.
More to the point because in a description (which is optionally per the PDF spec) I can use special characters UTF16BE basically which is not suited for serving as an id IMHO.

In theory you should be able to extract the attachment of this file using attachment.Desc instead of attachment.ID
only this will not work because of the description you get is already processed for display.
I am nor sure if pdfcpu should provide a workaround for this, I would need to see other PDF files with attachments using the description for the Nametree key.


```
   33: was compressed 32[1] generation=0 pdfcpu.Dict type=Filespec
<<
	<Desc, (Az E-TST-2020-10 sz�mla adatait tartalmaz� xml f�jl.)>
	<EF, <<
		<F, (31 0 R)>
		<UF, (31 0 R)>
	>>>
	<F, (1_E-TST-2020-10.xml)>
	<Type, Filespec>
	<UF, (1_E-TST-2020-10.xml)>
>>
   34: was compressed 32[2] generation=0 pdfcpu.Dict
<<
	<Names, [(Az E-TST-2020-10 sz�mla adatait tartalmaz� xml f�jl.) (33 0 R)]>
>>
```
```
Go-> pdfcpu info documents.pdf
         PDF version: 1.5
          Page count: 1
           Page size: 21.00 x 29.70 cm
............................................
               Title:
              Author:
             Subject:
        PDF Producer: XeTeX 0.99992; modified using iText® 5.1.3 ©2000-2011 1T3XT BVBA
     Content creator: LaTeX with hyperref package
       Creation date: D:20200713122701+02'00'
   Modification date: D:20200713122701+02'00'
............................................
              Tagged: No
              Hybrid: No
          Linearized: No
  Using XRef streams: Yes
Using object streams: Yes
         Watermarked: No
............................................
           Encrypted: No
         Permissions: Full access
         Attachments: 1_E-TST-2020-10.xml (Az E-TST-2020-10 számla adatait tartalmazó xml fájl.)
Go-> pdfcpu a l documents.pdf
1_E-TST-2020-10.xml (Az E-TST-2020-10 számla adatait tartalmazó xml fájl.)
Go->
```

**Comment by sagikazarmark** [comment]
I have seen a couple examples, primarily in PDF outputs of different invoicing software.

I assumed that calling extract attachments without id filters would have a performance penalty, but I'm not so sure anymore. I'm fine with that as a workaround for now.

**Comment by sagikazarmark** [comment]
@hhrutter do you think it would make sense to at least mention this somewhere in the documentation?

**Comment by hhrutter** [comment]
Are you referring to attachments that are internally stored by their description?
Like I said I consider this to be a corner case and off spec until I see evidence that shows me otherwise.

Have you tried to attach something using Acrobat Writer? That would tell us more.
If Acrobat attaches files using their description (again the spec says the description is optional) then I would go back and refactor attachment handling.

Cheers,
Horst

**Comment by sagikazarmark** [comment]
I agree that it's an edge case and as I mentioned I can easily work around it, but apparently some tools work this way out there and the reason I brought it up is because the API currently is a bit confusing: the attachment struct's `ID` field is technically not the same as the ID passed to `ExtractAttachments`, but one can easily jump to the opposite conclusion because they are named the same.

IMHO at least documenting the fact (or even better: renaming `ID` to something like `Name` or `FileName`) would resolve that confusion. Under the hood, pdfcpu can still use the file name as the attachment ID.

Sadly, I don't have access to adobe acrobat to try it. My guess would be that it stores the file by the file name, but that doesn't change the fact that nor the documentation neither the API communicates this issue correctly.

**Comment by hhrutter** [comment]
Thanks for the input.
I will take another look at this.

**Comment by sagikazarmark** [comment]
awesome, thanks!

**Comment by hhrutter** [comment]
Have a look at `func TestAttachmentsLowLevel` in api/test/attachments_test.go

Please describe your problem.

**Comment by sagikazarmark** [comment]
What do you mean?

I just pointed out that the function definition and documentation don't match [here](https://github.com/pdfcpu/pdfcpu/commit/ad6c2cc834d2aa6b9e0c7cf36b90114dd72f5cc5#diff-ea0e2674cb5d6ea70ea44b2ba765a9d15d13deb84efb649b13d42cc83ed57671R351)
