### ISSUE TITLE
Draw to PDF (QrCode)

### ISSUE THREAD

**Issue by JeffCorporation** [pdfcpu/pdfcpu#254]
I would like to add qrcode to pdf files. I found the DrawAndFillRect func which should meet my needs for drawing the QrCode matrix directly. However I cannot find a way to link this function to a context.

A way of adding an image.Image to a watermark/stamp could also be an option.

I'm hoping someone could give me some tips.
Kind regards

**Comment by hhrutter** [comment]
Hello,

pdfcpu`s PDF creation layer is implemented on a need to use basis and its primary purpose at the moment 
is drawing a textbox. That's why the creation infrastructure you are looking for is not there or hidden in private funcs
but this does not mean that what you want to do can't be done:

I think what you want to do is to loop over:

`func FillRect(bb *bytes.Buffer, rect *Rectangle, c SimpleColor) `

as in the following function where 4 colored rectangles are drawn to fill the margin for a textbox where we want to do this:

```
func drawMargins(buf *bytes.Buffer, c SimpleColor, colBB *Rectangle, borderWidth, mLeft, mRight, mTop, mBot float64) {
	SetLineWidth(buf, 0)
	SetStrokeColor(buf, c)

	r := RectForWidthAndHeight(colBB.LL.X+borderWidth, colBB.LL.Y+borderWidth, colBB.Width()-2*borderWidth, mBot)
	FillRect(buf, r, c)

	r = RectForWidthAndHeight(colBB.LL.X+borderWidth, colBB.Height()-borderWidth-mTop, colBB.Width()-2*borderWidth, mTop)
	FillRect(buf, r, c)

	r = RectForWidthAndHeight(colBB.LL.X+borderWidth, colBB.LL.Y+borderWidth+mBot, mLeft, colBB.Height()-2*borderWidth-mTop-mBot)
	FillRect(buf, r, c)

	r = RectForWidthAndHeight(colBB.UR.X-borderWidth-mRight, colBB.LL.Y+borderWidth+mBot, mRight, colBB.Height()-2*borderWidth-mTop-mBot)
	FillRect(buf, r, c)
}
```

Both are located in `create.go`.
Also take a look at `create_test.go` and the corresponding [output PDFs](https://github.com/pdfcpu/pdfcpu/tree/master/pkg/samples/create).

Basically what you need to do is populate a Page object, like in this function:
```
func createTestUserFontJustified(mediaBox *pdf.Rectangle) pdf.Page {
	p := pdf.NewPage(mediaBox)
	var region *pdf.Rectangle
	writecreateTestUserFontJustified(p, region)
	return p
}
```

The buffer you want to write is wrapped into the Page:
```
type Page struct {
	MediaBox *Rectangle
	Fm       FontMap
	Buf      *bytes.Buffer
}
```

Then create_test.go: `func createXRefAndWritePDF` demonstrates how you can write your page to a PDF file quickly.

* Image watermarks/stamps are already there if you need them.
* I am aware a `func drawImage()` might be useful and not too difficult to implement but a general PDF generation facility per se is not part of pdfcpu's mission statement - at least not for the foreseeable future.

Let me know how it goes &
Thank you for using 💚

**Comment by JeffCorporation** [comment]
I ended up using `ImageWatermark` to add the a QR Code image.

Here is a snippet: https://gist.github.com/JeffCorporation/654153190ab76fbce6a4012aa244eee4

The final code will pass the image to pdfcpu using to a ` ioutil.TempFile`. It's not optimal, but will do.
Thank you Horst
