### ISSUE TITLE
split: missing required resource subdict: ColorSpace

### ISSUE THREAD

**Issue by zhumengyifang** [pdfcpu/pdfcpu#280]
cmd: 
   pdfcpu split 193300d5165c7dbb36e7fa297db810b2.pdf demo
output information:
   pdfcpu: page 1: missing required resource subdict: ColorSpace

But this PDF will open normally ,also make watermarks

**Comment by hhrutter** [comment]
Hello!

If the output PDF looks ok in your PDF reader then you can ignore this.

This may be a bug either in pdfcpu's resource consolidation or a missing ColorSpace resource in the original.
The only way to find out is if you can provide a sample so we can reproduce this and possibly provide a fix.

Thanks for reporting this 💚

**Comment by zhumengyifang** [comment]
[JavaScript高级程序设计（第4版）.pdf](https://github.com/pdfcpu/pdfcpu/files/5819050/JavaScript.4.pdf)

**Comment by hhrutter** [comment]
This file reports a different problem caused by an empty name tree but is fixed with the latest commit.

**Comment by zhumengyifang** [comment]
Hello:
          the pdf in 0.3.8 version has error also ,the fixed in next version 0.3.9?

**Comment by hhrutter** [comment]
Hello!

This fix is for your file Javascript.pdf.
I could not check the initial problem because Javascript.pdf. does not have it.
It has a different one, that is fixed.

You can 

1) fetch latest and then go install to make your own binary
or
2)  wait until release 0.3.9 and get the binary from the release page but this will take a few days.
or 
3)
Send me a sample PDF that has this error:
```
cmd:
pdfcpu split 193300d5165c7dbb36e7fa297db810b2.pdf demo
output information:
pdfcpu: page 1: missing required resource subdict: ColorSpace
``` 
and I take another look.

Thank you!

**Comment by zhumengyifang** [comment]
thanks!
