### ISSUE TITLE
stamp: Add page numbers via format string

### ISSUE THREAD

**Issue by iilyak** [pdfcpu/pdfcpu#297]
Sometimes the original pdf doesn't have page numbers. It would be great if booklet printing mode would allow insertion of page numbers with configurable offset.

**Comment by hhrutter** [comment]
I am assuming you expect to add the page numbering via the cli because you can already do this with a little Go program:
See [stampVersatile_test.go](https://github.com/pdfcpu/pdfcpu/blob/master/pkg/api/test/stampVersatile_test.go)

This sounds like a variation of the stamp command. Offering a page numbering on the command line is tricky because every user has a different understanding about it or specific requirements.

You may also have to offer a format string to achieve something along the lines of: "1 of 20" or "page 3".

**Comment by iilyak** [comment]
> I am assuming you expect to add the page numbering via the cli

Yes via CLI

> Offering a page numbering on the command line is tricky because every user has a different understanding about it or specific requirements.
> You may also have to offer a format string to achieve something along the lines of: "1 of 20" or "page 3".

Good point. Might be hard to design and implement.

**Comment by hhrutter** [comment]
It is doable and if a valuable feature worth the effort but I need to think more about this 🤔 
Usually when you author the content yourself you can take care of the page number on the source document eg Word etc.
So I'm curious what's your specific usecase?

**Comment by iilyak** [comment]
I am receiving a pdf from a tutor who is not very tech savvy. She creates the pdf to be printed as a booklet on both sides of a paper. The pdf doesn't have page numbers. Quite often the printed paper falls off from the printer and I have a big trouble getting all pages back in order. I print on linux without decent print GUI and don't have UI elements in print dialog to add page numbers.

**Comment by iilyak** [comment]
> I have a big trouble getting all pages back in order.

Because it is not a text, but a set of math problems to solve without explicit numbers to help with ordering.

**Comment by hhrutter** [comment]
We are adding an option to stamp page numbers directly in one go.

What this means is you can preprocess your PDF before applying the booklet command with something like this:
`pdfcpu stamp add -mode text "Page %p" "pos:bc, points:12, sc:1.0 abs, rot:0" in.pdf out.pdf`

**Comment by hhrutter** [comment]
Fixed with the latest commit.
Use `%p` for current page number and `%P`for total pages during stamping/watermarking.
