### ISSUE TITLE
Add ability to scale images using given scale factor

### ISSUE THREAD

**Issue by iilyak** [pdfcpu/pdfcpu#308]
I have a pdf which came out of my scanner. Unfortunately when I try to use booklet command I end up with very small images on each page. In this particular case I need to scale images about 800% before I attempt to create a booklet. I understand that my scanner is probably at fault and it shouldn't produce the images which need to be upscalled. However the pdf look fine in any pdf viewer. 

This problem could be solved if pdfcpu would support providing scale factor for each image. 

This feature also would help with adapting A4 pdf to be printed on a letter sized paper. Documents prepared for A4 format have too wide margins and too small font when printed on letter sized paper. Using 120% scale I should be able to reduce margins and increase font size. Then in the next pass I would convert the resulting document into a booklet.

**Comment by hhrutter** [comment]
I am assuming you want to create a booklet from a PDF file.
The command renders the pages as they are laid out in the original.
In your case I suggest cropping pages with too much white space using `pdfcpu crop` 
and then running the result through `pdfcpu booklet`.

As for another workaround  you can stamp an empty PDF with your pages since this command also supports scaling.

**Comment by iilyak** [comment]
I was able to scale pages using `crop` feature as you proposed. I am closing this issue since my problems seem to be related to other commands I use in my script.
