### ISSUE TITLE
Invalid date pdf

### ISSUE THREAD

**Issue by jerem17** [pdfcpu/pdfcpu#327]
Hello !

First of all, thank you for all the hard work, it's really fantastic!

However, I noticed that I had a problem with some pdf.
When using pdfcpu's GOLANG API to count the number of pages, some PDFs (very rare) come out in error with this problem:

`pdfcpu: validateDateObject: <1/25/2021 00:26:39> invalid date`

my code : 
```
		docBytesReader := bytes.NewReader(b.Bytes())
		conf := pdfcpu.NewDefaultConfiguration()
		nbPages, err := api.PageCount(docBytesReader, conf)
```

I understood that it was therefore because of my date format, but is there a way to disable date validation? Knowing that I just want to retrieve the page count on a PDF.

Thank you :)

**Comment by hhrutter** [comment]
All pdfcpu operations rely on a valid input PDF file and during validation the page counter is calculated.
That's why you can't just skip validation.

PDF Dates follow: YYYYMMDDHHmmSSOHH ' mm 
You can look that up in the PDF spec.

I am sorry I don't have better news for you.
Thank you for using pdfcpu 💚
