### ISSUE TITLE
booklet/nup: handle existing page rotation

### ISSUE THREAD

**Issue by adamgreenhall** [pdfcpu/pdfcpu#349]
When reading a pdf that has been rotated (either using pdfcpu or some other tool), `PageDims` (media box?) within pdfcpu doesn't seem to know about the rotation.

Example:

```
pdfcpu info test.pdf | grep "Page size"
           Page size: 612.00 x 396.00 points
pdfcpu rotate test.pdf 90 test-rotated.pdf
pdfcpu info test-rotated.pdf | grep "Page size"
           Page size: 612.00 x 396.00 points              <---- expecting 396.00 x 612.00 points
```

**Comment by adamgreenhall** [comment]
My use case is that I have a pdf that I'm trying to run through `pdfcpu booklet`, but it's rotated 90deg. As you might imagine, this causes problems. Trying to fix it by `pdfcpu rotate` or rotate in macos preview doesn't work.

Makes sense about the different pages having different dimensions/rotation.

**Comment by hhrutter** [comment]
I see. I need to go back and double check but I thought booklet was taking care of page rotation.
Any chance you can get me a sample?

**Comment by adamgreenhall** [comment]
So, I've been working on adding a few more booklet layouts for different orientations and bindings and which booklet layout you use depends on the page orientation (portrait or landscape) and the binding (long- or short-edge) you want. Like this:
![Screen Shot 2021-06-30 at 11 50 11 AM](https://user-images.githubusercontent.com/704919/124015364-6e60e680-d999-11eb-9ed5-5b4a038ce52a.png)

So being able to correctly detect the real page orientation from the rotation would be really handy.

I'll send you an example pdf on slack.

**Comment by hhrutter** [comment]
OK, so any existing rotation value != 0 for input file pages needs to be taken into account during the rendering phase on the new page like it is done for stamping. 

Unfortunately I was wrong. 😞  I thought that's already in there in: nup.go
Once it works for nup it will also work for booklets, since that command is just a variation of nup.

The general idea is to internalize the page rotation and carry it over into the content stream via a transform matrix.
See pdfcpu/stamp.go and the handling of wm.pageRot.

Since this is quite tricky it will not be part of the upcoming release that I am about to push.
Again 😞

**Comment by hhrutter** [comment]
This has been addressed with the latest commit.
