### ISSUE TITLE
stamp: specify absolute stamp width/height

### ISSUE THREAD

**Issue by krhubert** [pdfcpu/pdfcpu#352]
Usecase: 
I need to cover up a big chunk of text that is under the watermark, but I still want to keep the font relatively small (like 12).

I can set a x,y, and border for watermarks, but what would be great is to have been able to specify width/height along with x,y. An extra feature is to position the text inside the rect (left, right, top left, etc...).

**Comment by hhrutter** [comment]
While I am investigating this, here is an idea for a work around.

You could use two stamps on top of each other:
* The first stamp is used to cover up a specific area using a dummy text and fill color = background color
* The second stamp contains your text using your preferred font size.

**Comment by krhubert** [comment]
Hi @hhrutter,
>While I am investigating this, here is an idea for a work around.

Actually, this is what I have been doing so far, but the accuracy of that solution is not satisfying. 
Let me know if I can help you someone with this feature.

**Comment by austinhjones** [comment]
This would be a really helpful feature @hhrutter do you happen to have an ETA on it?

**Comment by hhrutter** [comment]
Difficult. Firstly I would like to see detailed usecases upfront and also if this is needed on the api only or also on the cli.

I also would need to make a decision as far as keeping the api consistent because we have three types of stamps, text, image or PDF page based stamps.

**Comment by krhubert** [comment]
Let me share a use case and a sample PDF. I'm creating a service similar to [docusign](https://www.docusign.com/) or [hellosign](https://www.hellosign.com/). They allow to drag and drop some fields and then a backend service replaces them with actual text values. So on a fronted app, a user can specify also the rectangle size to hide what's below the field.

On the 2nd page of the [template.pdf](https://github.com/pdfcpu/pdfcpu/files/6815484/template.pdf), I also describe what I want to achieve.

Let me know if that's clear enough or you want me to prepare more detailed usecases.

**Comment by hhrutter** [comment]
* Your approach to deliver a signed document is to overwrite the tempate title? 
* Is that or will that document get signed electronically in the process?
* Where will your positioning rectangle come from? from a UI?
* Do you intent do do backend integration or cli scripting?

.. I don't see a usecase for pdfcpu stamping here.
With stamping the focus is the boundingbox of the stamp content be that text, an image or some external PDF page.
The bounding box is just that, the smallest rectangle enclosing the stamping content region.
There is margin and border width to make some space within the bounding box but these are limited ways and won't get you where you want to go with this I am afraid.

In general absolute positioning on a PDF page
..is tricky, since what you really see when you open a PDF page usually is the page content area defined by the cropbox or the mediabox if there is no cropbox. Most people are not aware of this so there is a potential for confusion
and there may be other things going on like a specified page UserUnit <> 1.0 which may complicate things.
The focus of the stamping api/cli is ease of use, that's why absolute positioning was avoided intentionally.
For positioning understanding the PDF page boundaries like they are defined in the PDF spec is indispensable, but
most users don't want to bother with these details.

This is more a usecase for PDF generating.
pdfcpu stamping relies on a couple of low level create functions: create_test.go is a good starting point where all create samples are generated(see the link above). There are functions for drawing and filling rects but it is all low level.
Generating PDFs has not been the focus of pdfcpu but you are free to use what's in create.go - which is also used by stamp.go. All the code you need for drawing a eg. your template is there. 

I can't stress enough to have a look at [samples/create](https://github.com/pdfcpu/pdfcpu/tree/master/pkg/samples/create)

**Comment by krhubert** [comment]
> Your approach to deliver a signed document is to overwrite the tempate title?
Yes, overwrite the template title

> Is that or will that document get signed electronically in the process?
No, I don't need to electronically sign the doc

> Where will your positioning rectangle come from? from a UI?
From the frontend, user can drag & drop a rectangle (and set it's size) in UI (we use `@react-pdf-viewer/core` + custom solutions)
 
> Do you intent do do backend integration or cli scripting?
It's done completely via backend integration.

I found a perfect solution, draw an image and that solves all the problems.

```go
func docFieldToRectWatermark(f domain.CustomSignDocField) (*pdfcpu.Watermark, string) {
  fimg, err := os.CreateTemp("", "pdfcpu-wm-*-white-rect.png")
  if err != nil {
    return nil, ""
  }
  defer fimg.Close()

  img := image.NewRGBA(image.Rect(0, 0, f.Width, f.Height))
  draw.Draw(img, img.Bounds(), &image.Uniform{color.RGBA{255, 255, 255, 255}}, image.Point{}, draw.Src)
  if err := png.Encode(fimg, img); err != nil {
    return nil, fimg.Name()
  }

  wm := pdfcpu.DefaultWatermarkConfig()
  wm.Mode = pdfcpu.WMImage
  wm.FileName = fimg.Name()
  wm.Pos = pdfcpu.TopLeft
  wm.Rotation = 0
  wm.Diagonal = pdfcpu.NoDiagonal
  wm.Dx = f.X
  wm.Dy = f.Y
  wm.Scale = 1
  wm.ScaleAbs = true
  wm.InpUnit = pdfcpu.POINTS
  wm.OnTop = true
  wm.Page = f.Page
  return wm, fimg.Name()
}
```

The only thing that can be improved here is to be able to pass a byte slice instead of a file to watermark conf. That would reduce the time to generate a pdf and will keep the code a bit cleaner.

So this feature can be closed. I just want to ask is it possible to pass a slice of bytes to `api` pkg. I can write this PR if you think it's ok to merge such solution.

**Comment by hhrutter** [comment]
Excellent! Since you are working below the api just pass an io.Reader to wm.Image and you are done
but then this is where my free support stops. :-)
