### ISSUE TITLE
dict=fdDict entry=Lang: unsupported in version 1.4

### ISSUE THREAD

**Issue by kaiceo** [pdfcpu/pdfcpu#412]
pdfcpu watermark add -mode image -- "static/img/wm.png" "sc:1 rel, rot:0" static/test/2017.pdf out.pdf
writing out.pdf...
dict=fdDict entry=Lang: unsupported in version 1.4
This file could be PDF/A compliant but pdfcpu only supports versions <= PDF V1.7

**Comment by hhrutter** [comment]
Hi!
Your input file is possibly malformed.
Making it pass validation is going to be difficult without a sample in order to reproduce this.
If you can share this file please do so either her or you can send me an email.
A stacktrace produced via: `pdfcpu validate -vv 2017.pdf &> crash.log` is also helping.

**Comment by hhrutter** [comment]
Closed due to inactivity.
