### ISSUE TITLE
[feature request] cli edit outline

### ISSUE THREAD

**Issue by lublak** [pdfcpu/pdfcpu#436]
Allow to add/list/remove/replace outlines via cli.

**Comment by hhrutter** [comment]
Hello!

Can you tell us your usecase?

**Comment by lublak** [comment]
My usecase is that i need to replace alot of relative links in multiple pdfs files.
An outlines can also have a link .
This feature request also comes from the same use case: https://github.com/pdfcpu/pdfcpu/issues/435

**Comment by hhrutter** [comment]
Just so I can better understand your usecase.
Can you share a PDF with outlines with links.
People have different understanding of the term *outline*

**Comment by lublak** [comment]
@hhrutter https://raw.githubusercontent.com/lublak/pdfdataextract/main/test/outline.pdf
![grafik](https://user-images.githubusercontent.com/44057030/157435560-5404816c-bee2-43f9-8d3b-f9859716c0a1.png)

**Comment by hhrutter** [comment]
This is opinionated and I maybe wrong.. 
I have not seen a lot of outline item dicts with actions and consider these more exotic.
While it is true that outline item dicts may include a destination or an action the implementation 
sticks to the common use case for local bookmarks using destinations.

Adding bookmarks/outlines is an API-only fature because these are organized hierarchically and
there is not an easy way to handle such input from the CLI other than via JSON perhaps.

**Comment by af** [comment]
> there is not an easy way to handle such input from the CLI other than via JSON perhaps

IMO being able to add bookmarks/outline via the CLI by passing a json file would be super helpful. For my use-case anyways :) Thanks for pdfcpu by the way, it's great!

**Comment by hhrutter** [comment]
Fixed! => https://github.com/pdfcpu/pdfcpu/releases/tag/v0.5.0
