### ISSUE TITLE
Create PDF

### ISSUE THREAD

**Issue by frederikhors** [pdfcpu/pdfcpu#450]
I apologize in advance for opening an issue, but I cannot understand and therefore I think it is an issue anyway. 😄

I have an application in Go and I would like to understand if this package can create a pdf FROM SCRATCH; I don't want to modify an existing one.

I would like to create for example a table with lines, an invoice, an A4 sheet with an email.

It's possible?

**Comment by hhrutter** [comment]
Hi there!

You can create your PDF files from scratch via JSON on the CLI using the [create](https://pdfcpu.io/generate/create) command.

Unfortunately because documentation is lacking it takes some playing around using this test:
https://github.com/pdfcpu/pdfcpu/blob/master/pkg/api/test/createFromJSON_test.go

which uses these JSON input files:
https://github.com/pdfcpu/pdfcpu/tree/master/pkg/testdata/json

to create these PDF files:
https://github.com/pdfcpu/pdfcpu/tree/master/pkg/samples/create

The create command supports an iterative (design) approach meaning you may 
process the result PDF using some new input JSON in order to add content on top of your existing content.

This is not an excuse for missing documentation but the JSON syntax is intuitive.

Have fun with pdfcpu 💚

**Comment by hhrutter** [comment]
Closed due to inactivity.

**Comment by nnzv** [comment]
It would be more flexible to create PDFs line by line from scratch like we do using the gofpdf package.

**Comment by hhrutter** [comment]
Please elaborate.

**Comment by nnzv** [comment]
I currently use `gofpdf` for creating PDFs in Go. Considering gofpdf's deprecated status, I'm exploring the possibility of using `pdfcpu` for similar functionality. Take, for example, the following code:

```go
package main

import "github.com/jung-kurt/gofpdf"

func main() {
	// Create a new PDF document
	pdf := gofpdf.New("P", "mm", "A4", "")
	// Add a page to the PDF
	pdf.AddPage()
	// Set font and size
	pdf.SetFont("Arial", "B", 16)
	// Add text to the PDF
	pdf.Cell(0, 10, "Hello, World!")
	// Output the PDF to a file (in this case, output.pdf)
	pdf.OutputFileAndClose("output.pdf")
}

```
