### ISSUE TITLE
PDF watermark from Reader

### ISSUE THREAD

**Issue by vsenko** [pdfcpu/pdfcpu#472]
Looks like currently it's impossible to create PDF watermarks via Reader (or byte slice, etc.), only from file: https://github.com/pdfcpu/pdfcpu/blob/e89570a4cdffa2129e927ae3aedf1f30cfdc7795/pkg/pdfcpu/stamp.go#L1192

It would be really handy to add such a feature. Furthermore it's already there  for Image watermarks: https://github.com/pdfcpu/pdfcpu/blob/e89570a4cdffa2129e927ae3aedf1f30cfdc7795/pkg/pdfcpu/stamp.go#L1224

**Comment by hhrutter** [comment]
Hello!

I am not quite sure what you are looking for.
Please explain your specific usecase.

In case you are looking for something similar to:
`api.ImageWatermarkForReader(r io.Reader, desc string, onTop, update bool, u pdfcpu.DisplayUnit)`

maybe:
`api.PDFWatermarkForReader(r io.Reader, desc string, onTop, update bool, u pdfcpu.DisplayUnit)`

then that can't be done.

A PDF resource for stamping/watermarking is a combination of some content stream bytes, its resources and a bounding box whereas an Image resource can be repesented by a simple byte slice. 

On top of that pdfcpu supports multi-stamps where each page of the input PDF gets stamped with a different page of the  PDF stamp source file. See more here: https://pdfcpu.io/core/stamp

**Comment by vsenko** [comment]
Excuse me for being that brief, consider the following usecase: the watermark is generated on-the-fly for each incoming PDF from some metadata, thus it's inconvenient to save the watermark beforehand to the file. The code that generates the watermark is on another process/host.

Thank you for identifying the problem with `io.Reader` approach, but maybe we can go with `io.ReadSeeker`:
```
api.PDFWatermarkForReader(r io.ReadSeeker, desc string, onTop, update bool, u pdfcpu.DisplayUnit)
```

**Comment by vsenko** [comment]
Another option (to keep the interface more consistent) is to copy data from `io.Reader` into `io.ReadSeeker` under the hood, but it will require twice more memory during the copy.

**Comment by hhrutter** [comment]
Generating a pdfcpu PDF watermark somewhere in order to use it later on for stamping is a valid use case but can't be done easily. 

Like already expained above, a PDF watermark is a non trivial object consisting of some content bytes, its resources and some metadata. Sure, we could write out this object/blob as a file, but this is not practical because of its required resources, especially when some embedded user fonts are involved. A much better alternative is to to render the PDF watermark to an image but that's not an option right now. 

Switching from io.Reader to an io.ReadSeeker doesn't change anything AFAIC.

**Comment by hhrutter** [comment]
This is part of https://github.com/pdfcpu/pdfcpu/releases/tag/v0.6.0
