### ISSUE TITLE
API can't change metadata author and title

### ISSUE THREAD

**Issue by suwro** [pdfcpu/pdfcpu#476]
Hello, I have to use LibreOffice to convert from different formats to pdf. Some documents has lots of questionmarks on metadata, title or author wich is wrong. The pdf content is viewed in browser's pdf view plugin that set's title from pdf metadata title.

I tried this but no succes

```
	ctx, err := api.ReadContextFile("in.pdf")
	ckErr(err)

	ctx.Author = "Fixed author"
	ctx.Title = "Fixed title"

	err = api.ValidateContext(ctx)
	ckErr(err)

	err = api.WriteContextFile(ctx, "out.pdf")
	ckErr(err)
```

I have no errors, just when opening the out.pdf the title and author is not changed.

**Comment by hhrutter** [comment]
Hello!

You have to use the `pdfcpu properties` command then check the result with  `pdfcpu info`.
You may use the cli or the api.

This may help: 
https://pdfcpu.io/properties/properties_add
https://github.com/pdfcpu/pdfcpu/blob/master/pkg/api/test/properties_test.go
#424 

If it still does not work then maybe because of some metadata dict in your file.
As of now pdfcpu is processing the `infoDict `only and your metadata may take precedence.

**Comment by suwro** [comment]
Thank you, I managed to change the title - most important one 👍 

```
	pdfcpu.PropertiesRemove(ctx.XRefTable, []string{"Title"})
	properties := map[string]string{"Title": "modified ok"}
	pdfcpu.PropertiesAdd(ctx.XRefTable, properties)
```
