### ISSUE TITLE
Info about publication language

### ISSUE THREAD

**Issue by vinser** [pdfcpu/pdfcpu#500]
Many book publishers set language of a publication. It will be nice to get it with api.Info()

**Comment by hhrutter** [comment]
Can you point me to a sample?

**Comment by vinser** [comment]
You may download free publication samples here: [English](https://www.freeditorial.com/en/books/the-adventures-of-sherlock-holmes)- `en`, [Spainish](https://www.freeditorial.com/es/books/las-aventuras-de-sherlock-holmes) -`es`

**Comment by petervwyatt** [comment]
There is some subtlety here: the Document Catalog **Lang** key reflects the _default_ language of the document, but this is not necessarily the _only_ language in the document. Indeed there doesn't even have to be ANY content in the document in this language since all text strings, logical structure elements, and marked content can override this. You often see this when different language office-type documents are saved: the document catalog setting seems to reflect the language of the office suite application, but the entire document content is completely different. So relying on this is fraught... 

See also https://pdf-issues.pdfa.org/32000-2-2020/clause07.html#Table29

**Comment by vinser** [comment]
@petervwyatt 
IMO 
For an ordinary user who has several dozen books at his disposal, usually in his native or English language, or a corporation's workflow, the availability of information about the language of publication is not essential. But for large online catalogs that distribute books on a paid or free basis, the presence of such information can significantly improve the user experience for international projects by providing language search. 
The lack of language info may be one of the reasons why many independent online catalogs prefer to use the epub format and variations of the mobi format.
It would be nice to get language with api.Info()

**Comment by hhrutter** [comment]
There is the catalog *Lang* entry or a metadata stream containing something like:
```
<dc:language>
     <rdf:Bag>
         <rdf:li>es</rdf:li>
      </rdf:Bag>
</dc:language>
```

Unfortunately these pieces of information are optional and not reliable as pointed out by @petervwyatt 
There is also a chance of contradicting info if both are available and as of now pdfcpu is not parsing metadata xml.

**Comment by vinser** [comment]
@hhrutter and  @petervwyatt
Thank you for your time and such detailed explanations. 
I'll do my best to guess language with something like  https://github.com/endeveit/guesslanguage
