### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by mbrevda** [pdfcpu/pdfcpu#507]
Would be great to have binaries published to npm to allow for easy incorporation into JS-based projects. A JS wrapper API (perhaps coupled with the output from https://github.com/pdfcpu/pdfcpu/issues/506) or js bindings would also be helpful!

Thanks!

**Comment by hhrutter** [comment]
Hello!
Please explain as detailed as possible what all of that means and maybe we can make it happen.
In general though smth like this is out of scope.

**Comment by mbrevda** [comment]
Sure. The npm is the default repository for all javascript libraries. While this project isn't js per se, publishing the binaries there allows for users to easily import pdfcpu to their project using the same tooling (i.e. `npm`) as they would for any other dependency. There is generally a helper script that ensures that the binary for the correct platform is installed. Here are some examples of such a script:

- [General example](https://blog.xendit.engineer/how-we-repurposed-npm-to-publish-and-distribute-our-go-binaries-for-internal-cli-23981b80911b)
- [esbuild](https://github.com/evanw/esbuild/blob/master/lib/npm/node-install.ts)
- [Chrome](https://github.com/puppeteer/puppeteer/blob/main/src/node/install.ts) (via puppeteer)

The overall benefit is that distribution becomes OS independent. From a security perspective, distributing via an official package prevents malicious actors from typo-squatting the package name and pilferage personal data (via reading the pdf's being processed or otherwise).

In addition to publishing the binaries, adding an official API can lead to greater adoption by offering simpler usability (for js users).

**Comment by G2G2G2G** [comment]
> Please explain as detailed as possible what all of that means and maybe we can make it happen.

JavaScript is a trash language so nearly all of the important things are made in different languages (websockets, reading files, doing any file manipulation, basically anything/everything) and JS just calls upon them (same as Python & PHP do mostly as well) 

He's basically asking for a wrapper around this so JS can control it.. should be done by him though as a separate project as all you'd need is to either run this via js or use this as a go pkg and run a go binary that listens for input and gives output

>The overall benefit is that distribution becomes OS independent.

it already is
> From a security perspective, distributing via an official package prevents malicious actors from typo-squatting the package name and pilferage personal data (via reading the pdf's being processed or otherwise).

not really an issue, even cryptographic libraries have messed up names because of other names being taken lmao

**Comment by hhrutter** [comment]
Out of scope.
