### ISSUE TITLE
Adding Chinese watermark does not take effect

### ISSUE THREAD

**Issue by triverment** [pdfcpu/pdfcpu#525]
wm, _ := pdfcpu.ParseTextWatermarkDetails("中文水印专用", "points:18", true, 18)
api.AddWatermarksFile("2022.pdf", "out1.pdf", nil, wm, nil)

Adding Chinese watermark does not take effect
The sample code is as follows：

wm, _ := pdfcpu.ParseTextWatermarkDetails("中文水印专用", "points:18", true, 18)
api.AddWatermarksFile("2022.pdf", "out1.pdf", nil, wm, nil)

**Comment by hhrutter** [comment]
Hi!

If you don't specify a font, pdfcpu defaults to Helvetica, which will not display chinese glyphs.
You need to pass in your desired userfont (that youhave installed before with `pdfcpu install myfont.ttf`).

Just follow the Userfont section in: https://pdfcpu.io/core/stamp and your stamp should work.

**Comment by triverment** [comment]
thanks!
After installing SimSun.ttf, it is ok!

**Comment by triverment** [comment]
thanks!
After installing SimSun.ttf, it is ok!

**Comment by 260721735** [comment]
here's an unconventional approach
```
func Init() {
	Configuration := model.NewDefaultConfiguration()
	fontDir := "your dir" // such as /User/private/font
        fontPath:="your path" // such as /User/private/font/your.ttf
	font.UserFontDir = fontDir
	err = font.LoadUserFonts()
	if err != nil {
		panic(err)
	}
	err = font.InstallTrueTypeFont(fontDir, fontPath)
	if err != nil {
		panic(err)
	}
}
```
you can use your private ttf in code like this. but it will be error when you exec model.NewDefaultConfiguration() in other func. the reason is font.UserFontDir get covered in https://github.com/pdfcpu/pdfcpu/blob/master/pkg/pdfcpu/model/configuration.go#L243.
i think it is sufficient to execute it only once during initialization.  EnsureDefaultConfigAt is concurrent unsafe. use sync.Once will be better
