### ISSUE TITLE
Uncaught Error: pdfcpu: checkStmv: unsupported "St…pu: supportedCFEntry: invalid entry "Length": 256

### ISSUE THREAD

**Issue by seanaye** [pdfcpu/pdfcpu#533]
### Thank you for submitting a possible bug!

Please ensure the following:

* Your issue is based on the latest commit - yep! `github.com/pdfcpu/pdfcpu v0.3.14-0.20221101223428-07d97625e3fa`
* State your OS and OS version: MacOS - arm64 v12.6 compile target `GOOS=js GOARCH=wasm`
* When reporting a problem with a specific PDF input file please avoid stating the organization responsible for the PDFWriter - just refer to the *PDFWriter*

Follow up to #532 

Certain files are unable to be decrypted with pdfcpu. I receive the titular error, and if I disable the length check I receive an invalid `getR() = 6`

Here is an example of an invalid file.
 
[encrypttest.pdf](https://github.com/pdfcpu/pdfcpu/files/10169532/encrypttest.pdf)

Correct password is `helloworld` and the file opens correctly in Preview (MacOS)

**Comment by petervwyatt** [comment]
This PDF has a few issues:
* the header is "%PDF-1.7" but the DocCatalog/**Version** key value is /1.4 - it is not valid to "downgrade" the PDF version in this way and the file needs to be treated as PDF 1.7
* the Crypt Filter is using the proprietary but publicly available Adobe Extension Level 3 to ISO 32000-1:2008, but the PDF is missing the **Extensions** dictionary in DocCatalog which declares this feature. See https://www.pdfa.org/resource/pdf-specification-index/ for documentation.
* a few font descriptor objects (5410, 5411, 5412) have positive values for **Descent** - these need to be negative
* a few font descriptor objects (5411, 5412) have bit 8 set for **Flags** - all undefined flag bits should be zero. Remember also: bit numbering in the PDF spec is 1-based.

**Comment by seanaye** [comment]
is there a way that pdfcpu can fix these issues "automagically"? I realize that from pdfcpu point of view this input file is invalid. I am trying to integrate pdfcpu in end user software that needs to "just work" e.g. Preview can decrypt the file fine

**Comment by skececi** [comment]
Following up here (thanks @hhrutter and @petervwyatt!), this file that @seanaye linked can be decrypted and loaded in Preview, Acrobat, Google Chrome, Firefox, and using Apache PDFBox for decryption.

For some context: we are trying to move away from Apache PDFBox (Java) and use PDFCpu in it's place, but running into these issues.

**Comment by hhrutter** [comment]
Hello and thanks 🙏  for being a sponsor! 

This is the result of pdfcpu's default PDF encryption  (AES,256 bits) :

```
<CF, <<
			<StdCF, <<
				<AuthEvent, DocOpen>
				<CFM, AESV3>
				<Length, 32>
			>>>
		>>>
		<Filter, Standard>
		<Length, 256>
		<O, <C5535CA44A3ED2709923B2A697101FFA5A55E906C53AF147057A5DF008CAC359B61406A03FDBED3CD5F623424EE34A13>>
		<OE, <09DBB43079B1C4A77C5CEB33C443C1EF0FAF172701C85E26AE3035F47ABCEFA3>>
		<P, -3901>
		<Perms, <21273D9E53002B216417E87CABD3C483>>
		<R, 5>
		<StmF, StdCF>
		<StrF, StdCF>
		<U, <95573579BB6CFFBC6AEC88A73FA744EB0F2E44CEBDDAF9C145FC8B2E3C2A057F5D8E30CEB7A445D6DF05985CA833286F>>
		<UE, <37A96B4D8CC0747F16E6E99BC9D2919AF2B0BEF339C9D5BF4F4D85D277F3230B>>
		<V, 5>
```

and here is the encryption dict of your test file:
```
<CF, <<
		<StdCF, <<
			<CFM, AESV3>
			<Length, 256>
		>>>
	>>>
	<Filter, Standard>
	<Length, 256>
	<O, <AE965FE45CFB30E78B95ED418EAA07D13649447181F00ED04CD70227AEF4B03B9C4930A271C1AD4A9AA2D14E0B5CF028>>
	<OE, <7FE615B26312A8857F26657762D6264DE97C016028056A65DAC23F6BA7B35AE8>>
	<P, -4>
	<Perms, <06B59B6770B7B2A2E666E5E038250465>>
	<R, 6>
	<StmF, StdCF>
	<StrF, StdCF>
	<U, <318EFC6607D63CEF85E4A7FC1430300401729CEC83B494329B44DF37AE6E2F4C0691777DD8E59E5765EF2644D6D9CD3E>>
	<UE, <9A6E53D6F0F3DDA74B1E85DEBB59BBB8A5BD98AA89B04D760160554ABA6CF984>>
	<V, 5>
```

As you can see the difference is the "Length 256" in the StdCF dict and "R=6".
Since any R value (the standard security handler revision) above 5 is not supported in PDF 1.7 pdfcpu has to assume the PDF in question was written in any PDF version above 1.7.

Actually the spec goes until 128 bit AES (using R=4) but since that's not the kind of encryption you would want to see these days pdfcpu goes a little bit out of the 1.7 spec box and also supports 256 bit AES (R=5), because it is straightforward to implement.

Anything beyond that is not supported by pdfcpu until we move into PDF 2.0 territory which I expect to happen next year.

This really is what you should be getting if you want to decrypt your file with pdfcpu:
```
Go-> pdfcpu dec i533.pdf
writing i533.pdf...
pdfcpu: PDF 2.0 encryption not supported
Go->
```
or `ErrUnknownEncryption` respectively if you call into pdfcpu's api. 
The correct handling will be in the upcoming release.

pdfcpu is (still) a PDF 1.7 processor.
Although there seem to be numerous people using pdfcpu in production - pdfcpu is still Alpha.
I am here to support you but your mileage may vary..

Another thing.. 
All these PDF viewers out there are fault tolerant PDF parsers to some degree attached to a renderer. 
Although pdfcpu does the best it can to be tolerant the competition is ongoing..
I am sorry I don't have better news for you.

Thanks again for using pdfcpu 💚

**Comment by petervwyatt** [comment]
Just to be clear: this is not PDF 2.0, but an Adobe proprietary extension to PDF 1.7 (ISO 32000-1:2008) that is publicly defined which is why it is widely supported. I will leave it to @hhrutter to decide if he wishes to extend pdfcpu to support those PDF 1.7 extensions...

PS. PDF 2.0 did adopt many of these Adobe Extensions but sometimes with changes...

**Comment by hhrutter** [comment]
for now out of scope.
