### ISSUE TITLE
cli: form fill

### ISSUE THREAD

**Issue by kben** [pdfcpu/pdfcpu#571]
### Thank you for submitting a possible bug!

Please ensure the following:

* Version v0.4.0 - CLI
* Linux

Getting the following error when trying to fill a third party from
`writing x.pdf...
pdfcpu: dict=<<
	<AP, <<
		<N, (751 0 R)>
	>>>
	<DA, (/Helv 12 Tf 0 g)>
	<F, 4>
	<FT, Tx>
	<Ff, 29360128>
	<MaxLen, 8>
	<P, (741 0 R)>
	<Rect, [248.73 665.30 368.78 688.56]>
	<Subtype, Widget>
	<T, (Textfield)>
	<TU, (853 0 R)>
	<Type, Annot>
	<V, (��TEST)>
>> entry=MK missing.
`

Steps to reproduce:
* wget https://www.aok.de/pk/magazin/cms/fileadmin/pk/rheinland-hamburg/pdf/antrag-leistungen-pflegeversicherung.pdf
* pdfcpu form expot antrag-leistungen-pflegeversicherung.pdf 
* EDIT out.json and modify a Textfield value
* pdfcpu form fill antrag-leistungen-pflegeversicherung.pdf out.json x.pdf
  > above error.

**Comment by hhrutter** [comment]
The issue with this particular file should be fixed with the latest commit!

**Comment by kben** [comment]
Thanks for the fix. I don't get the error anymore, but no Textfield is filled after executing the fill command.

Another question, is it possible to also export the corresponding "ID" of the form element?

**Comment by hhrutter** [comment]
The exported `id` corresponds with the `name` column in `pdfcpu form list`. (I need to fix this)
If you are using the latest commit then re-export your json and them fill this should be working in A.Reader.
A.Reader is the reference for validity of the pdfcpu form commands.

**Comment by kben** [comment]
Now let's discuss it. What do you think about exporting also the object number, so we have the "name" and object number in the json/struct?

**Comment by hhrutter** [comment]
So this revolves around the topic of consistent naming across the board.
I have been thinking quite a lot about this lately.

The spec defines `field names` whereas for exporting and filling what we really need is a reference point, an `id`.
The naming has to be consistent across `pdfcpu form list`,  `export` and `fill`.
I have decided for `name` like it is currently done in `pdfcpu form list` to be consistent with the spec.
Hence as per the next commit `form export` will use `name` instead of `id` for identifying fields
as also will this be corrected on the CLI usages of the various `form`commands.

About exporting an obj#:
I am really unsure - maybe you can enlighten me -  about what we would gain by exporting the object number of a field.
First of all it is subject to change with every subsequent saving of the PDF.
Secondly there may be deep hierarchies of non-terminal fields, either intentionally or as a result of merging several PDF forms. In these scenarios which obj# do you want the top one the terminal fields one?

Ideally and as per UI design I would like to get away without co ITnfronting CLI users with object numbers as far as the form processing workflow. It's just really distracting to also have to think about obj# when I only want to to do a quick form fill.

**Comment by hhrutter** [comment]
👍  Obviously people don't have form filling in mind when they author PDF forms.
No one really bothers with field ids that make sense and this can get really ugly during filling..

Still - while it may work for simple forms - it would be misleading to use the object number in general as a replacement for the field id.

**Comment by enahs** [comment]
@hhrutter I have another example of this behaving poorly — is there a way can share the form with you privately?

**Comment by hhrutter** [comment]
sure -> hhrutter@gmail.com
but keep in mind the form processing feature was implemented for forms created by pdfcpu foremost.

**Comment by hhrutter** [comment]
This is fixed with the latest release.
