### ISSUE TITLE
Dynamic font size based on textbox width

### ISSUE THREAD

**Issue by hrushya07** [pdfcpu/pdfcpu#698]
Trying to fill pdf with `pdfcpuapi.FillFormFile(inFilePDF, inFileJSON, outFilePDF, conf)` by this i’m able to fill pdf,

But you can check in below image 
<img width="564" alt="image" src="https://github.com/pdfcpu/pdfcpu/assets/85426572/b6e27e8c-87c9-46ae-8813-15c517556e76">

Here text is big and it is going outside the textfield, it should adjust font size automatically to fit inside that text box
Lets say we have put text as - this text field should fit automatically respect to text box width adjusting font size inside text box but you can see some part of it but it should automatically adjust its size based in its width and should show whole line.
Like 
<img width="609" alt="image" src="https://github.com/pdfcpu/pdfcpu/assets/85426572/b9526bd3-0679-4d42-b837-308d059d4ec2">

I can only see we can change font, it size also orientations when we have to add stamp/watermark
Is this feature not available yet for filling it in text box with auto font size? or am i missing something

**Comment by hhrutter** [comment]
Hello!

When you design a form you need to think about which values you want to support for each individual form field.
Also you need to think about a maximum length for input strings and then appropriately opt for simple textfields or multi line text fields - that's just part of the design process.

Automatically resizing the input font in order to fit in your whole data is not recommended and also not part of the specification as I recall. The idea is, if the length of your input data was justified but it does not fit using the defined form font/size then the author of the form would have provided a multi line field or a wider field in the first place.

Another aspect is adjusting the font size may lead to unreadable form field content.

If you are filling somebody else's form and your input data does not fit then this is just how the form was designed. 
You should always be able to scroll right to the end of your text data string and of course there should not be a problem saving it to disk.
