### ISSUE TITLE
 pdfcpu: validateOutlineTree: non-empty outline item dict needs "Count" <> 0

### ISSUE THREAD

**Issue by chun222** [pdfcpu/pdfcpu#709]
```go
err := api.AddAttachmentsFile("WO00000000000215.pdf", "", []string{"hello.pdf"}, true, nil) 
``` 
error : 
pdfcpu: validateOutlineTree: non-empty outline item dict needs "Count" <> 0

[WO00000000000215.pdf](https://github.com/pdfcpu/pdfcpu/files/12582067/WO00000000000215.pdf)

**Comment by chun222** [comment]
The pdf file I created with wkhtmltopdf cannot add attachments

**Comment by chun222** [comment]
i test `model.ValidationNone`  ,it be ok
```golang
	config := model.NewDefaultConfiguration()
	config.ValidationMode = model.ValidationNone

	// 创建一个新的PDF处理器
	err := api.AddAttachmentsFile("WO00000000000215.pdf", "", []string{"hello.pdf"}, true, config)
	fmt.Println(err)
```

**Comment by hhrutter** [comment]
Hello!

I may be very mistaken, but here is the explanation for the error you are getting:

```
21:   offset=    2542 generation=0 types.Dict type=Outlines
<<
	<First, (22 0 R)>
	<Last, (22 0 R)>
	<Type, Outlines>
>>
```
A missing *Count* in the *Outlines* dict implies no open outline items.

```
22:   offset=    2420 generation=0 types.Dict
<<
	<Count, 0>
	<Dest, __WKANCHOR_2>
	<First, (23 0 R)>
	<Last, (23 0 R)>
	<Parent, (21 0 R)>
	<Title, (��y��S�ep)
>>
	
23:   offset=    2327 generation=0 types.Dict
<<
	<Count, 0>
	<Dest, __WKANCHOR_4>
	<Parent, (22 0 R)>
	<Title, (��h3111)>
>>
```

The PDF spec defines *Count* for outline item dicts so:

<img width="1235" alt="Screenshot 2023-09-12 at 09 26 56" src="https://github.com/pdfcpu/pdfcpu/assets/11322155/d21097b8-5969-4bfd-be3d-188e755f158f">

Since there are no open outline items pdfcpu expects a <Count, -1> for obj 22 and no count for obj 23.
