### ISSUE TITLE
Impossible to retrieve the attachments from a PDF in version 1.4

### ISSUE THREAD

**Issue by AmineZouitine** [pdfcpu/pdfcpu#953]
`pdfcpu` does not allow extracting attachments from a PDF in version 1.4.

### CLI Error:
```
> pdfcpu attachments list doc.pdf
unknown_error: facturx: validating xref table: pdfcpu: validateNameEntry: dict=rootDict entry=PageMode invalid dict entry: UseAttachment
```
### Lib issue:
```
unknown_error: facturx: validating xref table: pdfcpu: validateNameEntry: dict=rootDict entry=PageMode invalid dict entry: UseAttachments
```

I upgraded the PDF version to 1.7 with `Ghostscript`, and then it worked. So the issue was indeed due to the PDF version.

Library version: v0.8.1
CLI version: v0.8.1 dev

OS: MacOS

It would be great not to have this constraint anymore 🙏

**Comment by GitHubRulesOK** [comment]
VERSION is nothing to do with attachments (only related to PDF/A numbering)
What likely happened is GS always writes a new file with little or no errors thus should have altered the file into a workable format

tested with a file that says 1.4 compatible (no error) as the file was written in the past by GhostScript thus you need to look closer as to why your source PDF file fails but version is rare as a cause.

```
pdfcpu_0.8.1_Windows_i386>pdfcpu attachments list facture-x-1.4.pdf
factur-x.xml (ZUGFeRD electronic invoice)
```

**Comment by hhrutter** [comment]
Hello!

pdfcpu maintainer here!

The PDF spec clearly defines the pagemode "UseAttachments" since PDF v1.6.

Since your file's version is 1.4 this is is a spec violation and has to be reported.

**Comment by GitHubRulesOK** [comment]
I am confused /UseAttachments is a viewer control it does not have to have an attachment here is 1.1 from PDFA discussion with /UseAttachments view https://github.com/pdf-association/pdf-issues/files/11260962/out.pdf

Whilst not trawling back to 1.1
 I see no reason to reject its presence in older version numbers
Tthe viewing state is not related to "is attachment allowed or not" clearly PDFA 1a and 1b dont allow attachments but that should not affect the setting of the viewer or should it ?

**Comment by petervwyatt** [comment]
That is correct - ISO 19005 (PDF/A) does not prohibit private data (including key values of documented keys) so long as they do **_not_** impact page rendering visual appearance. In this case, it is just a viewer UI recommendation. You can consider it "private" since it wasn't formally documented until much more recently - as per resolved [PDF Errata 275](https://github.com/pdf-association/pdf-issues/issues/275) which is where the mentioned attachment is from - [resolution wording](https://pdf-issues.pdfa.org/32000-2-2020/clause12.html#Table147).

See also our recent publication ["_Understanding Private Data in PDF/A_"](https://pdfa.org/resource/understanding-private-data-in-pdf-a/) for more info.

**Comment by hhrutter** [comment]
This issue is not about the catalog entry _ViewerPreferences_.

It's about catalog entry _PageMode_:

The validation for this very file fails because it sets _PageMode_ to UseAttachments and this is prohibited by the spec until v1.6:
<img width="532" alt="Screenshot 2024-09-26 at 11 15 40" src="https://github.com/user-attachments/assets/66969907-c763-4e9c-a409-26d2120a2b22">

If this sounds like a contradiction then maybe it needs to be addressed in [PDF Errata 275](https://github.com/pdf-association/pdf-issues/issues/275)

**Comment by petervwyatt** [comment]
That may be what the spec said, but Adobe implemented the otherwise undocumented setting in its products since it was introduced - and so had other vendors to match behaviour. Thus there are extant files in the wild with this value from that era. All PDF 2.0 has done is acknowledge this fact and make the defacto spec official. View it as an editorial oversight dating back many years :-)
