### ISSUE TITLE
Error pdfcpu: parse: corrupt string literal, possibly unbalanced parenthesis

### ISSUE THREAD

**Issue by Rae93** [pdfcpu/pdfcpu#979]
OS: macOS Sonoma 14.0

Hi ! Thank you for your beautiful feature. I am trying to stamp a pdf file using api in the pkg.
It has this error `pdfcpu: parse: corrupt string literal, possibly unbalanced parenthesis` on `api.ReadAndValidate`.
Here are the error when I do `pdfcpu val -vv ss.pdf` in the cli:
<img width="738" alt="image" src="https://github.com/user-attachments/assets/ef308083-d78e-46aa-9b90-ad5c6176c9d1">
[e.log](https://github.com/user-attachments/files/17584673/e.log)

I also attached the example pdf file that I tested
[ss.pdf](https://github.com/user-attachments/files/17582169/ss.pdf)

Thank you so much for the help !

**Comment by hhrutter** [comment]
Thanks for reporting this!

**Comment by hhrutter** [comment]
Adobe Reader has a problem reading this file:
<img width="602" alt="Screenshot 2024-11-03 at 11 47 28" src="https://github.com/user-attachments/assets/de2e8ca3-826b-4e3b-b65c-b67e237dab71">

And rightfully so, because it features `DA` string literals that are not correctly escaped.
The responsible party is the PDF Producer.

Other PDF Viewers can open the file w/o problem but that does not necessarily mean they parse it correctly when they skip checking `DA` entries in annotations.

So I am not really sure what to do about this.
We could relax validation and skip parsing `DA` but that sounds risky to me.

**Comment by Rae93** [comment]
Thank you so much for the investigation !
Your point is valid and I think you should not relax the validation. Closing this issue
